### ISSUE TITLE
Audit Trail

### ISSUE THREAD

**Issue by ianpurton** [bionic-gpt/bionic-gpt#122]
## Todo

- [x] Form doing full refresh
- [x] Rename items in sidenav
- [x] Get an icon
- [x] Tidy up filter
- [x] Is filter working
- [x] Add tests
- [ ] Pagination?
- [x] Open up RLS for sys admin
- [ ] Make first user that registers an admin (trigger?)
- [x] Add audit for prompts web
- [ ] Add audit for pompts API

## Requirements

- Only for system admins? Actually why not let everyone see it.
- Show usage for API keys
- Find users with most API calls
- How do we measure usage? tokens?
- Can we count tokens per second
- Active users
- Can we implement with postgres triggers?

## Example trigger

```psql
CREATE FUNCTION audit_create_team() 
   RETURNS TRIGGER 
   LANGUAGE PLPGSQL
AS $$
BEGIN
   -- trigger logic
  INSERT INTO audit_trail VALUES('CreateTeam', current_user()....
END;
$$

CREATE TRIGGER create_team
   AFTER INSERT
   ON organisation_uuser
   FOR EACH ROW
       EXECUTE PROCEDURE audit_create_team
```

## Tables

```sql
CREATE TYPE audit_access_type AS ENUM (
    'API', 
    'UserInterface'
);

CREATE TYPE audit_action AS ENUM (
    'AddMember', 
    'DeleteMember', 
    'CreateInvite',
    'RemoveTeamMember',
    'CreateTeam',
    'DeleteTeam',
    'CreateAPIKey',
    'RevokeAPIKey',
    'TextGeneration'
);

CREATE TABLE audit_trail (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    user_id INT NOT NULL, 
    organisation_id INT NOT NULL, 
    access_type audit_access_type NOT NULL,
    action audit_action NOT NULL,
    description VARCHAR NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_organisation
        FOREIGN KEY(organisation_id) 
        REFERENCES organisations(id)
        ON DELETE CASCADE
);

CREATE TABLE audit_trail_text_generation (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    audit_id INT NOT NULL, 
    prompt_id INT NOT NULL, 
    tokens_sent INT NOT NULL,
    tokens_received INT NOT NULL,
    time_taken INT NOT NULL,

    CONSTRAINT fk_prompt
        FOREIGN KEY(prompt_id) 
        REFERENCES prompts(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_audit
        FOREIGN KEY(audit_id) 
        REFERENCES audit_trail(id)
        ON DELETE CASCADE
);

COMMENT ON TABLE audit_trail IS 'Log all accesses to the system';
COMMENT ON COLUMN audit_trail.user_id IS 'The user that accessed the system';
COMMENT ON COLUMN audit_trail.access_type IS 'How was the system accessed i.e. by the CLI or web interface etc.';
COMMENT ON COLUMN audit_trail.action IS 'The action committed. i.e. deleting a secret etc.';
COMMENT ON COLUMN audit_trail.description IS 'A text description of what happened';


COMMENT ON TABLE audit_trail_text_generation IS 'For text generation we capture extra information';
```
