### ISSUE TITLE
Model usage statistics - API usage

### ISSUE THREAD

**Issue by ianpurton** [bionic-gpt/bionic-gpt#124]
## Requirements

- Get a feel for how the system is being used
- Be able to find who/what is behind any high load.

## Possibilities

- [ ] On API screen show calls in last 24 hours for each key
- [ ] On models screen show a graph of calls per hour for each model.
- [x] On models screen, show top 10 users with GUI and API stats.

## Graphs

- https://github.com/tiby312/poloto-project

## Todo

- [ ] Create a query to get model stats.
- [x] Same for users
- [x] Show as a table initially?
- [ ] create the graph.

## SQL

Top users in the lat 24 hours

```sql
SELECT 
    at.user_id,
    SUM(attg.tokens_sent) AS total_tokens_sent
FROM 
    audit_trail AS at
JOIN 
    audit_trail_text_generation AS attg ON at.id = attg.audit_id
WHERE 
    at.created_at >= NOW() - INTERVAL '24 HOURS'  -- Filter for the last 24 hours
GROUP BY 
    at.user_id
ORDER BY 
    total_tokens_sent DESC;
```
