### ISSUE TITLE
Use `kind` instead of `docker-compose.yml` for trialling Bionic.

### ISSUE THREAD

**Issue by ianpurton** [bionic-gpt/bionic-gpt#290]
`docker-compose.yml` gives us several issues.

- We have to maintain our own keycloak and envoy images
- We're struggling to keep both the infra as code and the docker compose in sync.

## Advantages of Kind

- It's closer to an actual production deployment
- Get's more people testing our infra as code
- Less to maintain.

## Disadvantages of Kind

- One more thing for users to install
- We already use docker compose for our integration testing.
- Will take a while to setup
- Most people already have docker installed.
- Possible instability as users on different platforms test it out.
- We will have to create a docker with the infra + config to create deployments.

## Blockers

- [ ] How do we manage GPU?

## Work Breakdown

- [ ] Get existing config working with kind.
- [ ] New infra-as-code container
- [ ] Switch integration testing over to kind (or create a new test)
- [ ] Test on windows, linux and apple silicon.
- [ ] Change docs.
