### ISSUE TITLE
fix: Integration Testing via EKS?

### ISSUE THREAD

**Issue by 9876691** [bionic-gpt/bionic-gpt#336]
## Todo - CI/CD

- [x] How do we know when all pods are ready?
- [x] Access postgres from devcontainer
- [x] Can we run in selenium
- [x] Install mailhog
- [ ] Fix up the tests
- [ ] Install selenium when using --testing
- [x] Open the selenium ports. Nodeport
- [ ] Run tests in integration-testing.yaml

## Todo - Development

- [x] Somehow pass in IP address
- [x] Run tests from IDE
- [x] Open ports used during development
- [x] cornucopia 
- [x] Open the selenium ports. Nodeport
