### ISSUE TITLE
fix: Upgrade functionality in the Operator

### ISSUE THREAD

**Issue by 9876691** [bionic-gpt/bionic-gpt#469]
## Notes

- Leave secrets in place
- Use apply in installer
- Share code with installer
- Leave DB in place
- Leave CNPG and Nigix operators in place.

## Todo

- [x] Test if server side apply works
- [x] Only create DB if it doesn't already exist.
- [x] How do we do apply instead of create?
- [x] Test install still works
- [x] Should we copy secrets to pgadmin?
- [x] Only run deletes if resource exists
- [ ] Add upgrade page to docs
