### ISSUE TITLE
UI/UX Enhancements

### ISSUE THREAD

**Issue by 9876691** [bionic-gpt/bionic-gpt#473]
## Todo

- [ ] Make app responsive
- [ ] History titles generated by model
- [ ] Image generation
- [ ] i18n
- [ ] Thumbs up/down
- [ ] Examples in the console i..e 4 boxes
- [ ] Speach?
- [ ] Describe image? (no idea wht the use case is for this.)
