### ISSUE TITLE
Simplify the tryout process

### ISSUE THREAD

**Issue by 9876691** [bionic-gpt/bionic-gpt#482]
Can we get to a docker run for users who just want to try it out?

- Run multiple processes https://github.com/malyn/groundcontrol
- https://github.com/just-containers/s6-overlay

## Todo

- [x] Bring back docker compose? https://github.com/bionic-gpt/bionic-gpt/blob/50993cf5578f7f6cf6c83ffe09a91bbfc769c4dc/docker-compose.yml
- [x] Make the user registration set secure headers
- [ ] Show email invite links.
