### ISSUE TITLE
Get streaming working in docker-compose

### ISSUE THREAD

**Issue by 9876691** [bionic-gpt/bionic-gpt#502]
Issue is possible here - https://github.com/purton-tech/barricade/blob/master/crates/actix-server/src/main.rs#L204

## Todo

https://github.com/bionic-gpt/bionic-gpt/tree/b8bfc1cf1a27e949ef743a58527ee9146acb7f07

- [x] Use old envoy container?
- [x] A configurable / route. 
- [x] index.rs always redirects to /auth/sign_up
- [x] A new route /app/post_registration
- [x] Routes set with env var.
- [x] Build envoy container
- [x] Update docker-compose.yml
