### ISSUE TITLE
Need ability to share datasets with Company level

### ISSUE THREAD

**Issue by tiswas247** [bionic-gpt/bionic-gpt#569]
### Discussed in https://github.com/bionic-gpt/bionic-gpt/discussions/568

<div type='discussions-op-text'>

<sup>Originally posted by **tbendien** August 21, 2024</sup>
We created Assistants with datasets that we want to share at Company level, but this is not an option in the GUI.

Please add the ability to share data sets at Company level e.g. for HR policy, IT info, those types of company wide us cases. </div>

## Todo

- [x] Add 'Company' visibility to dataset form.
- [x] Check the SQL do we already take this into account.
- [x] chnage to upsert
- [x] Change new to form
- [x] Test chnaging visibility
- [x] Only sys admin can set to company.
- [x] Test and see in UI.
- [x] Change Company text to Enterprise or perhaps Me Only, My This Team, Everyone
- [x] Create a Private prompt with a global dataset - Does it work?
- [x] Ability to edit dataset (If you have access)

**Comment by tbendien** [comment]
This would be a very helpful feature:

"Change Company text to Enterprise or perhaps Me Only, My This Team, Everyone"

**Comment by tbendien** [comment]
This issue is still open as we have not figured out how to manually set this permission and also a GUI update might be needed. Thank you :-)
