### ISSUE TITLE
Assistant Improvements

### ISSUE THREAD

**Issue by tiswas247** [bionic-gpt/bionic-gpt#647]
## Architecture for Image Upload

- Store images on s3 i.e. minio.
- Is there something already available?
- Resize images on upload
- Rust server just passes through to service
- https://github.com/mstgnz/cdn
- Configure backups to minio

## Todo

- [x] sql for image update/insert and retrieve

```sql
CREATE TABLE images (
    id SERIAL PRIMARY KEY,
    filename TEXT NOT NULL,
    file_url TEXT NOT NULL,  -- Path or URL where the image is stored
    content_type TEXT NOT NULL,  -- MIME type (e.g., image/png, image/jpeg)
    size BIGINT NOT NULL,  -- Size of the image in bytes
    uploaded_at TIMESTAMPTZ DEFAULT NOW()
);
```

- [x] Set the author field to a name/email.
- [x] My Assistants link should be a button
- [x] Set image on update
- [x] Show images
- [x] Show example prompts on view page
- [x] Only pull back users prompts
- [x] reduce image size before upload
- [x] Markdown in description?
- [x] My assistants page
- [x] Model drop down on chat not working
- [x] Defaukt body limit https://stackoverflow.com/questions/75205271/rust-axum-multipart-length-limit-exceeded
- [x] Database migration
- [x] index.rs tabs are not full width, screen is skewwiff
- [x] Add images
- [x] Cancel button on dialog
- [x] dialog is responsive on mobile
- [x] What if there are a lot other of categories
- [x] All tab, shows all assistant, but not there when assistants > 20
- [x] Buttons should be at the bottom

```sql
ALTER TABLE prompts ADD COLUMN image BYTEA;
```
