### ISSUE TITLE
New RBAC rule, can_make_assistant_public

### ISSUE THREAD

**Issue by tiswas247** [bionic-gpt/bionic-gpt#655]
## Todo

- [x] How to do the check
- [x] double check images with assistants
- [x] Don't show all tab if no assistants
- [x] Tidy up tab.
- [x] remove is_saas at least for assistants
- [x] Assistant/My Assistants link should be bold
- [x] Conversation starts, don't show if we don't have any
